name: IoTLessonsArduinoBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Compile By Arduino CLI Action
      - name: Compile Arduino Sketch
        uses: arduino/compile-sketches@v1
        with:
          # 
          fqbn: "arduino:avr:nano"
          
          # Path for Ino File
          sketch-paths: "./Lesson2HomeTask/sketch_jul7b"

	# path for save bin file
          cli-compile-flags: |
            - --output-dir
            - ./build_output
          
          name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
          # Name of archive
           name: arduinoBuilds
          # The folder whose contents will be packed into the archive (should match --output-dir above)
           path: ./build_output/
