name: IoTLessonsArduinoBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Створюємо папку для збереження артефактів
      - name: Create Build Directory
        run: mkdir -p build_output

      # Compile By Arduino CLI Action
      - name: Compile Arduino Sketch
        uses: arduino/compile-sketches@v1
        with:
          # Вказуємо конкретний процесор для Nano (ATmega328)
          fqbn: "arduino:avr:nano:cpu=atmega328"
          sketch-paths: "./Lesson2HomeTask/sketch_jul7b"
          cli-compile-flags: |
            --output-dir=build_output

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arduinoBuilds
          path: build_output/